### PR TITLE
Merged methods options in one single option.

### PR DESCRIPTION
**Pull request by Edujugon**
The component had 2 options with same name which was causing issues when declaring the component with prop config.
The method redraw was undefined since was declared in the first methods option. It's necessary for the watcher config.

### CODE REVIEW

**Comment by heygambo** [comment]
I have the same PR :)

https://github.com/vue-bulma/datepicker/pull/38

**Comment by jaybeecave** [comment]
Can we get this merged please?

**Comment by Kuchiriel** [comment]
Can we get this merged please?²

**Comment by bmf-san** [comment]
Please merge this p-r ...

**Comment by luventa** [comment]
Thanks! Merged pr #38 which has the same code change as @nerdyglasses mentioned.

**Pull request closed without merging**
